require: rubocop-rspec

AllCops:
  Exclude:
    - lib/templates/**/*
    - lib/scripts/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - bin/**/*
    - log/**/*
    - scripts/**/*
    - Rakefile
    - node_modules/**/*
    - '*.gemspec'
  TargetRubyVersion: 2.6.3

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  CountComments: false
  Exclude:
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

RSpec/ExampleLength:
  Max: 8

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 5

RSpec/MessageSpies:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false
